[docs] Re-wrote INSTALL.md
omapsapp/omapsapp pull request #134
Opened 2021-02-06 21:21 UTC by rtsisyk

Add actual instructions for desktop/android/ios.

2021-02-10 19:40 UTC, rtsisyk commented
@vng @int02h could you please validate updated instructions?

2021-02-16 20:09 UTC, andrewshadura requested changes
`Re-wrote` → `Rewrite` (commit summary needs to use imperative mood)

2021-02-16 20:15 UTC, andrewshadura requested changes

2021-02-16 20:15 UTC, andrewshadura commented on docs/INSTALL.md
> +Get a Linux or a Mac machine.
```suggestion
You need a Linux or a Mac machine to build OMaps.
```

2021-02-16 20:15 UTC, andrewshadura commented on docs/INSTALL.md
> +Get a Linux or a Mac machine.
```suggestion
You need a Linux or a Mac machine to build OMaps for Android.
```

2021-02-16 20:15 UTC, andrewshadura commented on docs/INSTALL.md
> +Get a Mac.
```suggestion
Building OMaps for iOS requires a Mac.
```

2021-02-16 20:15 UTC, andrewshadura commented on docs/INSTALL.md
> +Enroll [Apple Developer Program](https://developer.apple.com/programs/).
```suggestion
Enroll in the [Apple Developer Program](https://developer.apple.com/programs/).
```

2021-02-16 20:23 UTC, rtsisyk commented
Thanks, @andrewshadura! Have you tried to build the app by using these instructions?

2021-02-16 20:28 UTC, andrewshadura commented
> ! Have you tried to build the app by using these instructions?

Not yet, but I certainly will.

2021-02-18 10:29 UTC, andrewshadura submitted a review, later dismissed

2021-02-19 20:05 UTC, rtsisyk commented
Need to mention how to install qt && cmake on Mac.

2021-02-20 11:57 UTC, rtsisyk commented
@vng @biodranik please take a quick look. I try to actualize the build documentation based on my newbie experience.

2021-02-28 07:55 UTC, vng approved these changes

2021-02-28 07:55 UTC, vng commented on docs/INSTALL.md
> +sudo gem install cocoapods
I'd prefer here brew install cocoapods
sudo gem gives more troubles ..

2021-02-28 13:08 UTC, biodranik commented on docs/INSTALL.md
> +sudo gem install cocoapods
+1

2021-03-03 08:46 UTC, rtsisyk commented
Updated according to comments.

2021-03-03 21:06 UTC, vng approved these changes

2021-03-03 21:56 UTC, biodranik approved these changes
LGTM

2021-03-06 05:59 UTC, merged