Android: disable in-app purchases #48
omapsapp/omapsapp pull request #140
Opened 2021-02-10 12:43 UTC by Alteyaa

**Changes :** 
1. [android] disabled in-app purchases #48

2021-02-11 13:11 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +//  private void initControllersAndValidatePurchases(@Nullable Bundle savedInstanceState)
@Alteyaa we discussed with @vng that in this case it would be better to remove all unused part instead of commenting out them.

2021-02-11 13:12 UTC, rtsisyk requested changes
Please remove unused parts of code instead of commenting.

2021-02-12 17:50 UTC, Alteyaa commented on android/src/com/mapswithme/maps/MwmActivity.java
> +//  private void initControllersAndValidatePurchases(@Nullable Bundle savedInstanceState)
@rtsisyk okey

2021-02-20 14:41 UTC, rtsisyk commented
Replaced by #159

2021-02-20 14:41 UTC, closed without merging