[android] Set required NDK in build.gradle (the latest version does not compile yet)
omapsapp/omapsapp pull request #207
Opened 2021-03-08 21:29 UTC by biodranik

TODO: Integrate the latest Android NDK

2021-03-12 08:47 UTC, vng requested changes
Manual NDK is ok, but why we manually set cmake version?
We can remove cmake:version IMHO.

2021-03-12 13:07 UTC, biodranik commented
There are many cool options in newer cmake I want to use.

2021-03-12 13:08 UTC, biodranik commented
In this way we'll have predictable environments. Cmake with this version is already bundled in Android SDK.

2021-03-13 12:06 UTC, vng approved these changes

2021-03-13 12:07 UTC, vng commented
Here is CI check error:
```
CMake '3.18.1' or higher was not found in PATH or by cmake.dir property.
  - CMake '3.10.2' found in SDK could not satisfy requested version '3.18.1' because it was lower.
  - CMake '3.10.2' found in PATH could not satisfy requested version '3.18.1' because it was lower.
  ```

2021-03-13 15:03 UTC, rtsisyk requested changes
Please manage to fix CI.

2021-03-13 15:03 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
> +          (echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.18.1")
I don't know how to explain this, but it works via Android Studio, but doesn't work via command-line.

2021-03-13 20:28 UTC, biodranik commented
OK, removed cmake commits. We'll upgrade cmake later.

2021-03-13 20:29 UTC, merged