Cleanup iOS.
omapsapp/omapsapp pull request #99
Opened 2021-01-25 07:19 UTC by vng

2021-01-25 08:49 UTC, rtsisyk requested changes
1. Let's keep crashlytics, we need crash reports.
2. Please also remove Google && Facebook from Settings->OpenStreetMap Login

2021-01-25 09:01 UTC, vng commented on tools/autobuild/detect_qmake.sh
> +  ~/Developer/Qt/5.8/clang_64/bin/qmake \
Looks like this detect_qmake.sh is not needed any more .. I also don't have Qt/5.8

2021-01-25 10:56 UTC, rtsisyk commented on tools/autobuild/detect_qmake.sh
> +  ~/Developer/Qt/5.8/clang_64/bin/qmake \
Let's remove this script then.

2021-01-25 21:01 UTC, rtsisyk commented
The last, but not least: please accept [DCO](https://github.com/omapsapp/omapsapp/blob/master/docs/DCO.md) and add ["Signed-off-by" to each commit](https://github.com/omapsapp/omapsapp/blob/master/docs/CONTRIBUTING.md#pull-requests):

1. git rebase -i HEAD~[NUMBER OF COMMITS]
2. "reword"
3. append "Signed-of-by: Your real name <email>"

2021-01-26 18:13 UTC, rtsisyk approved these changes

2021-01-26 18:30 UTC, rtsisyk approved these changes

2021-01-26 18:30 UTC, merged